### ISSUE TITLE
Drupal code quality is failing for v1.3.0

### ISSUE THREAD

**Issue by lomasgupta** [hussainweb/drupalqa-action#15]
After upgrading to PHP 8.1. Drupal code quality is failing.
We have s/w the PHP version back to 7.4  ref: https://github.com/hussainweb/drupalqa-action#example-usage
The issue seems with PHPlint. Earlier it was 3.2 now after upgrading its 9.4
<img width="622" alt="Screenshot 2023-03-22 at 7 41 30 PM" src="https://user-images.githubusercontent.com/13271284/226931066-4ff9c8a6-3f0d-442e-8ad7-492391761439.png">

**Comment by hussainweb** [comment]
There was an update to `phplint` that has broken how arguments are passed. From the previous screenshot you shared, I could see that the `extensions` option was set to the string `"php,module,theme,engine,inc,install"` rather than an array as the command expects. I'll push a fix for this soon.
